/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      colors: {
        'on-error': '#490013',
        'on-primary-fixed-variant': '#370086',
        'primary': '#ba9eff',
        'background': '#060e20',
        'surface-tint': '#ba9eff',
        'tertiary-dim': '#40ceed',
        'inverse-on-surface': '#4d556b',
        'surface-dim': '#060e20',
        'on-primary-fixed': '#000000',
        'primary-fixed': '#ae8dff',
        'outline-variant': '#40485d',
        'on-surface-variant': '#a3aac4',
        'surface': '#060e20',
        'on-primary-container': '#2b006e',
        'secondary-dim': '#316bf3',
        'on-secondary-container': '#f8f7ff',
        'on-background': '#dee5ff',
        'secondary-container': '#0053db',
        'on-secondary-fixed': '#002d80',
        'on-tertiary-fixed': '#003640',
        'primary-container': '#ae8dff',
        'primary-fixed-dim': '#a27cff',
        'secondary': '#7799ff',
        'surface-container-lowest': '#000000',
        'surface-container-high': '#141f38',
        'on-tertiary-fixed-variant': '#005564',
        'secondary-fixed-dim': '#b0c2ff',
        'outline': '#6d758c',
        'surface-container-highest': '#192540',
        'secondary-fixed': '#c4d0ff',
        'on-secondary-fixed-variant': '#0047bd',
        'surface-variant': '#192540',
        'error-dim': '#d73357',
        'inverse-primary': '#6e3bd7',
        'on-primary': '#39008c',
        'surface-bright': '#1f2b49',
        'error': '#ff6e84',
        'on-error-container': '#ffb2b9',
        'tertiary-fixed-dim': '#40ceed',
        'on-tertiary-container': '#004b58',
        'on-secondary': '#001b55',
        'primary-dim': '#8455ef',
        'surface-container-low': '#091328',
        'tertiary-fixed': '#53ddfc',
        'inverse-surface': '#faf8ff',
        'on-tertiary': '#005464',
        'tertiary': '#8ce7ff',
        'tertiary-container': '#53ddfc',
        'on-surface': '#dee5ff',
        'error-container': '#a70138',
        'surface-container': '#0f1930',
        'dark-900': '#060e20',
        'accent': '#7799ff',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-up': 'slideUp 0.4s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px #6366f1, 0 0 20px #6366f1' },
          '100%': { boxShadow: '0 0 10px #ec4899, 0 0 40px #ec4899' },
        }
      },
      backdropBlur: {
        xs: '2px',
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
