-- Sample Users Data
INSERT INTO users (id, name, email, passwordHash, role, college, interests, createdAt) VALUES
('user-001', 'Arjun Kumar', 'arjun.kumar@srm.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'student', 'SRMIST RAMAPURAM', '["Hackathon", "Web Dev", "AI/ML"]', NOW()),
('user-002', 'Priya Singh', 'priya.singh@srm.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'student', 'SRMIST RAMAPURAM', '["Workshop", "Cybersecurity", "Data Science"]', NOW()),
('user-003', 'Vikram Patel', 'vikram.patel@srm.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'student', 'SRMIST RAMAPURAM', '["Coding Contest", "Robotics", "Web Dev"]', NOW()),
('user-004', 'Anjali Sharma', 'anjali.sharma@srm.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'student', 'SRMIST RAMAPURAM', '["Symposium", "AI/ML", "Competition"]', NOW()),
('user-005', 'Rohan Desai', 'rohan.desai@srm.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'student', 'SRMIST RAMAPURAM', '["Hackathon", "Summit", "Seminar"]', NOW()),
('user-006', 'Dr. Rajesh Kumar', 'rajesh.kumar@srm.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'organizer', 'SRMIST RAMAPURAM', '[]', NOW()),
('user-007', 'Prof. Meera Nair', 'meera.nair@srm.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'organizer', 'SRMIST RAMAPURAM', '[]', NOW()),
('user-008', 'Amit Sharma', 'amit.sharma@vit.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'organizer', 'VIT Chennai', '[]', NOW()),
('user-009', 'Neha Gupta', 'neha.gupta@anna.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'organizer', 'Anna University', '[]', NOW());

-- Sample Events Data
INSERT INTO events (id, title, description, date, time, location, college, organizer, category, posterUrl, registrationUrl, registrations, createdAt) VALUES
('event-001', 'TechFest Hackathon 2024', 'A 24-hour hackathon where students showcase their coding and innovation skills. Build something amazing!', '2024-04-20', '09:00 AM', 'Main Auditorium, SRM Campus', 'SRMIST RAMAPURAM', 'Dr. Rajesh Kumar', 'Hackathon', '/uploads/hackathon.jpg', 'https://forms.google.com/event-001', '["user-001", "user-003", "user-005"]', NOW()),
('event-002', 'Web Development Workshop', 'Learn modern web development with React, Node.js, and MongoDB. Perfect for beginners!', '2024-04-15', '02:00 PM', 'Computer Lab 1, Block A', 'SRMIST RAMAPURAM', 'Prof. Meera Nair', 'Workshop', '/uploads/webdev.jpg', 'https://forms.google.com/event-002', '["user-001", "user-002", "user-004"]', NOW()),
('event-003', 'AI/ML Symposium', 'Explore the latest trends in Artificial Intelligence and Machine Learning with industry experts.', '2024-04-22', '10:00 AM', 'Seminar Hall, Block C', 'SRMIST RAMAPURAM', 'Dr. Rajesh Kumar', 'Symposium', '/uploads/ai-ml.jpg', 'https://forms.google.com/event-003', '["user-004", "user-005"]', NOW()),
('event-004', 'Cybersecurity Bootcamp', 'Intensive bootcamp on ethical hacking and cybersecurity. Learn to protect against cyber threats!', '2024-04-18', '03:00 PM', 'Computer Lab 3, Block B', 'SRMIST RAMAPURAM', 'Prof. Meera Nair', 'Workshop', '/uploads/cybersec.jpg', 'https://forms.google.com/event-004', '["user-002"]', NOW()),
('event-005', 'Data Science Competition', 'Compete in data analysis and visualization challenges. Win exciting prizes!', '2024-04-25', '11:00 AM', 'Innovation Hub', 'SRMIST RAMAPURAM', 'Dr. Rajesh Kumar', 'Competition', '/uploads/datasci.jpg', 'https://forms.google.com/event-005', '["user-002", "user-004"]', NOW()),
('event-006', 'Robotics Workshop', 'Build and program robots using Arduino and Raspberry Pi. Hands-on learning experience!', '2024-04-21', '01:00 PM', 'Robotics Lab, Block D', 'SRMIST RAMAPURAM', 'Prof. Meera Nair', 'Workshop', '/uploads/robotics.jpg', 'https://forms.google.com/event-006', '["user-003", "user-005"]', NOW()),
('event-007', 'Code Sprint Challenge', 'Fast-paced coding competition. Solve problems and rank on the leaderboard!', '2024-04-19', '04:00 PM', 'Computer Lab 2, Block A', 'SRMIST RAMAPURAM', 'Dr. Rajesh Kumar', 'Coding Contest', '/uploads/codesprint.jpg', 'https://forms.google.com/event-007', '["user-001", "user-003"]', NOW()),
('event-008', 'Cloud Computing Seminar', 'Introduction to Cloud platforms: AWS, Azure, and Google Cloud. Industry professionals sharing insights.', '2024-04-23', '02:30 PM', 'Auditorium, Block C', 'SRMIST RAMAPURAM', 'Prof. Meera Nair', 'Seminar', '/uploads/cloud.jpg', 'https://forms.google.com/event-008', '["user-005"]', NOW()),
('event-009', 'Mobile App Development Summit', 'Build cross-platform mobile apps with Flutter and React Native. Expert talks and hands-on sessions.', '2024-04-24', '10:00 AM', 'Convention Center', 'VIT Chennai', 'Amit Sharma', 'Summit', '/uploads/mobile.jpg', 'https://forms.google.com/event-009', '["user-001", "user-004"]', NOW()),
('event-010', 'Tech Leadership Roundtable', 'Discussion with CTO and tech leaders about career growth in tech industry.', '2024-04-26', '05:00 PM', 'Executive Conference Room', 'Anna University', 'Neha Gupta', 'Seminar', '/uploads/leadership.jpg', 'https://forms.google.com/event-010', '["user-002"]', NOW());

-- Add more diverse users and events
INSERT INTO users (id, name, email, passwordHash, role, college, interests, createdAt) VALUES
('user-010', 'Sneha Reddy', 'sneha.reddy@srm.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'student', 'SRMIST RAMAPURAM', '["AI/ML", "Data Science", "Hackathon"]', NOW()),
('user-011', 'Karan Singh', 'karan.singh@srm.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'student', 'SRMIST RAMAPURAM', '["Web Dev", "Cybersecurity", "Workshop"]', NOW()),
('user-012', 'Divya Nair', 'divya.nair@vit.edu', '$2b$10$M1VFy59S8BQsS5qDLII5nOuwPRP0iw.IQwZQD.U7GvcE6zCn5uVN2', 'student', 'VIT Chennai', '["Robotics", "AI/ML", "Competition"]', NOW());

INSERT INTO events (id, title, description, date, time, location, college, organizer, category, posterUrl, registrationUrl, registrations, createdAt) VALUES
('event-011', 'Blockchain & Cryptocurrency Workshop', 'Deep dive into blockchain technology and cryptocurrency basics. Learn about smart contracts!', '2024-04-27', '03:00 PM', 'Tech Hub, Block E', 'SRMIST RAMAPURAM', 'Dr. Rajesh Kumar', 'Workshop', '/uploads/blockchain.jpg', 'https://forms.google.com/event-011', '["user-010", "user-011"]', NOW()),
('event-012', 'DevOps & CI/CD Pipeline Training', 'Learn Docker, Kubernetes, and automated deployment. Essential for modern development!', '2024-04-28', '11:00 AM', 'Computer Lab 4, Block B', 'SRMIST RAMAPURAM', 'Prof. Meera Nair', 'Workshop', '/uploads/devops.jpg', 'https://forms.google.com/event-012', '["user-001"]', NOW()),
('event-013', 'UI/UX Design Challenge', 'Design competition focusing on user experience and interface design. Showcase your creativity!', '2024-04-29', '09:00 AM', 'Design Studio, Block F', 'SRMIST RAMAPURAM', 'Dr. Rajesh Kumar', 'Competition', '/uploads/uiux.jpg', 'https://forms.google.com/event-013', '["user-002", "user-012"]', NOW()),
('event-014', 'Game Development Workshop', 'Create 2D and 3D games using Unity and Unreal Engine. Fun hands-on experience!', '2024-04-30', '02:00 PM', 'Game Dev Lab, Block G', 'SRMIST RAMAPURAM', 'Prof. Meera Nair', 'Workshop', '/uploads/gamedev.jpg', 'https://forms.google.com/event-014', '["user-003", "user-010"]', NOW()),
('event-015', 'IoT & Smart Devices Summit', 'Explore Internet of Things and build smart home devices. Future of connected systems!', '2024-05-01', '10:00 AM', 'Convention Center', 'VIT Chennai', 'Amit Sharma', 'Summit', '/uploads/iot.jpg', 'https://forms.google.com/event-015', '["user-004", "user-012"]', NOW());
